include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

.projecttest:
  extends: .test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH
    - julia --project=$CI_JULIA_PROJECT -e '
                          using Pkg;
                          Pkg.resolve();
                          Pkg.instantiate();
                          Pkg.build();
                          include("test/runtests.jl");'
.gputest:
  image: nvidia/cuda:10.1-devel
  extends: .projecttest
  tags:
    - nvidia
  variables:
    CI_JULIA_PROJECT: 'test/gpuenv'

.cputest:
  extends: .projecttest
  variables:
    CI_JULIA_PROJECT: 'test/testenv'

gpu:test:dev:
  extends:
    - .gputest
    - .julia:nightly
  allow_failure: true

cpu:test:dev:
  extends:
    - .cputest
    - .julia:nightly
  allow_failure: true

gpu:test:v1.1:
  extends:
    - .gputest
    - .julia:1.1

cpu:test:v1.1:
  extends:
    - .cputest
    - .julia:1.1

gpu:test:v1.2:
  extends:
    - .gputest
    - .julia:1.2

cpu:test:v1.2:
  extends:
    - .cputest
    - .julia:1.2

gpu:test:v1.3:
  extends:
    - .gputest
    - .julia:1.3

cpu:test:v1.3:
  extends:
    - .cputest
    - .julia:1.3

documentation:
  extends:
    - .documentation
    - .julia:1.3
  tags:
    - nvidia
  only:
    - master
    - staging
    - trying

pages:
  dependencies:
    - documentation
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master

